version: '3.5'

services:
  postgres:
    container_name: pg_fincheck
    image: postgres
    env_file:
      - ./.env
    ports:
      - '5432:5432'
    networks:
      - fincheck_pg_network
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_fincheck
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'

    ports:
      - '${PGADMIN_PORT:-5050}:80'
    networks:
      - fincheck_pg_network
    restart: unless-stopped

networks:
  fincheck_pg_network:
    driver: bridge
    name: fincheck_pg_network
